### ISSUE TITLE
Multiple messages

### ISSUE THREAD

**Issue by lukejpreston** [lukejpreston/xunit-viewer#10]
as per [Issue 6](https://github.com/lukejpreston/xunit-viewer/issues/6) you can get multiple messages so should support being able to show them all not just the first one

**Comment by lukejpreston** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="3" failures="1" errors="0" time="35" name="AllTests">
  <testsuite name="MathTest" tests="2" failures="1" errors="0" time="15">
    <testcase name="Addition" status="run" time="7" classname="">
      <failure message="Value of: add(1, 1)&#x0A; Actual: 3&#x0A;Expected: 2" type=""/>
      <failure message="Value of: add(1, -1)&#x0A; Actual: 1&#x0A;Expected: 0" type=""/>
    </testcase>
    <testcase name="Subtraction" status="pass" time="5" classname="">
    </testcase>
  </testsuite>
  <testsuite name="LogicTest" tests="1" failures="0" errors="0" time="5">
    <testcase name="NonContradiction" status="run" time="5" classname="">
    </testcase>
  </testsuite>
</testsuites>`

**Comment by Musta9bal** [comment]
Hi, could this issue be fixed ? It'll be nice to have a workaround

**Comment by lukejpreston** [comment]
When you say workaround I would suggest you do it in your xml

suppose you have

```xml
<testcase ...>
  <message>
    message 1
  </message>
  <message>
    message 2
  </message>
</testcase>
```

you could change this to

```xml
<testcase ... message="message 1 <br /> message 2"></testcase>
```

or

```xml
<testcase ...>
  <message>
    message 1
    message 2
  </message>
</testcase>
```

anything inside the `message=""` can be html

if you don't have control over the xml then there isn't a work around currently
