### ISSUE TITLE
Aborts prematurely when used in Node scripts

### ISSUE THREAD

**Issue by gpaciga** [lukejpreston/xunit-viewer#112]
This can't be used in a node script [as advertised](https://github.com/lukejpreston/xunit-viewer#usage-node), because the `process.exit()` call on line 34 of `xunit-viewer.js` causes the process to exit prematurely.

https://github.com/lukejpreston/xunit-viewer/blob/master/xunit-viewer.js#L34

If the xunit-viewer functionality is the only thing in the script, it won't matter, but if I want anything else to happen afterwards, even just a `console.log`, it will not work.

```
const xunitViewer = require('xunit-viewer')

const main = async () => {
  await xunitViewer({
    server: false,
    results: 'data',
    ignore: ['_thingy', 'invalid'],
    title: 'Xunit View Sample Tests',
    output: 'output.html'
  })
  console.log("The process exits before we can get to this line");
}
main()
```

I'm tempted to say we can just delete [line 34](https://github.com/lukejpreston/xunit-viewer/blob/master/xunit-viewer.js#L34), but I'm not familiar with the `server` or `watch` modes so don't know if they ever require it.

**Comment by lukejpreston** [comment]
This is a good point. Could you raise a PR with this suggestion, please?

**Comment by jimp100** [comment]
I have been experiencing this issue too.  Do you have an eta for a release containing this fix?

**Comment by lukejpreston** [comment]
@jimp100 thanks for the nudge on this :smile: 

Update to version 7.2.0 I have now added a`script` boolean to the arguments which will skip all exits but maintain the CLI functionality from before. The suggested fix, and the PR have issues with the CLI where certain combination of commands would either keep the command running or exit when you didn't want it to. This solution gets around all those issues I was having when testing Xunit Viewer.

There might be a better solution but it was getting a lot more complex.

**Comment by jimp100** [comment]
@lukejpreston - Many thanks for this.  I've updated the package, rejigged my code and everything looks good.
