### ISSUE TITLE
Cannot print from browser

### ISSUE THREAD

**Issue by dastbayoo** [lukejpreston/xunit-viewer#119]
Starting with version 7.1.8, I can no longer use the browser to print the report into a PDF (which is an important step in my workflow). Also true for version 7.1.9.

Up to version 7.1.7 I was able to generate an HTML report, open the browser, print the page to PDF hand have the whole content in the PDF as a result.

Starting with version 7.1.8, only the first few pages are rendered, the remaining pages are blank. This can also be reproduced with the demo page: https://lukejpreston.github.io/xunit-viewer/

**Comment by lukejpreston** [comment]
I didn't know anyone was using this to generate PDFs!
I can add a printable toggle which would
1. remove anything not needed for printing, e.g. search box
2. render everything, including not on the screen

**Comment by dastbayoo** [comment]
Once you put things in the open, you'll be surprised in what ways people will use it 😁 Anyway, thanks for all your work!

**Comment by lukejpreston** [comment]
@dastbayoo this is a ridiculous turnaround.
I finally have a solution for you in v9!

Depending on your browser, you should be able to print and save to PDF it will display all the test currently filtered before printing. If your browser doesn't support that there is a button in the menu on the right `FAST MODE` and clicking it will change it to `PRINT MODE` which will render everything filtered and you can print that page.

<img width="1383" alt="image" src="https://github.com/lukejpreston/xunit-viewer/assets/4129128/c3f4a01d-53b7-4b32-bb06-783ee85d07d1">

I am closing this now. If you have any issues with this please get in touch 😄
