### ISSUE TITLE
Expanding everything by default hurts usability when many tests are present

### ISSUE THREAD

**Issue by Holzhaus** [lukejpreston/xunit-viewer#133]
When viewing test results for thousands of tests, expanding everything is not really helpful. I'd suggest to detect if many tests results are present when generating the HTML file and collapsing elements by default when a certain threshold is exceeded.

**Comment by lukejpreston** [comment]
I fixed this a while ago but never replied. I will close this issue.
If anyone still has issues, please send me your XML files and browser, then I will see what I can do to help!
