### ISSUE TITLE
TypeError: files is not iterable

### ISSUE THREAD

**Issue by manjumaikan** [lukejpreston/xunit-viewer#146]
Raise any issues using GitHub and provide sample data where possible.

To help debug any issues please provide the following info

* node and npm version
v20.6.
* xunit viewer version
unknown
* browser
edge/chrome
* sample xml

If you have issue migrating from Junit Viewer or older version of Xunit Viewer please feel free to raise an issue titled **MIGRATION HELP**

There is a `v5` branch which maintained through Open Source PRs, this branch will not maintain `npm audit` issues

The cli  xunit-viewer -p 9202 -r /opt/goss/reports -s gives an error "TypeError: files is not iterable". 

Raised PR to fix the issue.
https://github.com/lukejpreston/xunit-viewer/pull/147

**Comment by lukejpreston** [comment]
merged now in version 10.5
