### ISSUE TITLE
New advance filter in v10.5.1 does not work at all

### ISSUE THREAD

**Issue by ldziadkowiec** [lukejpreston/xunit-viewer#149]
I miss the old v4 behavior, but we have not find any more usable reporter, so we are stuck with xunit viewer v4.
I have tried the new v10, hoping that quick filter for failed tests would be back and I was happy that the new dropdown has been introduced.
![obrazek](https://github.com/lukejpreston/xunit-viewer/assets/98472799/907189bb-9594-4cec-b6b8-a7b8a2eeac55)

But it does not work. It does nothing. Nothing changes when I switch the dropdown. I would expect the PASSED suites and tests to be hidden and only suites with FAILED tests would be present only with the FAILED tests.
![obrazek](https://github.com/lukejpreston/xunit-viewer/assets/98472799/11779517-34f4-4fa9-8def-22a3e7cbd3de)

**Comment by lukejpreston** [comment]
Ah sorry to see this I was hoping it would stop everyone needing to use v4 as well!
Please could you send a sample XML file so I can take a look and debug this further?

**Comment by lukejpreston** [comment]
It works in the demo https://lukejpreston.github.io/xunit-viewer if you are curious how it should be working

**Comment by lukejpreston** [comment]
@ldziadkowiec I was wondering if you are still having this issue and had time to see my question?

**Comment by lukejpreston** [comment]
Going to close, please reopen if anyone finds this still to be an issue
