### ISSUE TITLE
Opening the generated html page seems to have a default filter applied which hides the results

### ISSUE THREAD

**Issue by RoryDoherty** [lukejpreston/xunit-viewer#150]
If I open the generated html results file then I see this
![image](https://github.com/lukejpreston/xunit-viewer/assets/92513817/596c3d1c-ead3-4664-8dbe-8900aab835ac)

Selecting the filter button in the top right shows that the fourth option "Filtered is selected"
![image](https://github.com/lukejpreston/xunit-viewer/assets/92513817/92d03432-9d09-4636-a53e-8728a436e25e)

If I then change this to "All" or "Error/Failure/Unknown" then I can actually see the results:
![image](https://github.com/lukejpreston/xunit-viewer/assets/92513817/58fe0988-2e6d-4d02-abc7-4536f96eba06)

Would it be possible to change the default filtering option to always be "ALL" ?

To help debug any issues please provide the following info

* node and npm version
 npm: '8.19.4'
 node: '16.20.2'
* xunit viewer version
10.5.1
* browser
chrome
* sample xml

**Comment by RoryDoherty** [comment]
Thanks, that would be great!

**Comment by lukejpreston** [comment]
This is now the default in v10.6.0

**Comment by khalilTN** [comment]
Actually, we have the same issue, we want also that "Empty hidden" for suites be unchecked by default.
Is there way to do that by cli args ?

**Comment by koerbcm** [comment]
It would be nice to customize what the "default" filter would be via args/opts.
