### ISSUE TITLE
Getting [DEP0151] DeprecationWarning when using xunitViewer() in ES6 module

### ISSUE THREAD

**Issue by pradudev** [lukejpreston/xunit-viewer#151]
I am running the below code from inside an ES6 module file
`await xunitViewer({
      server: false,
      results: config.testReportXmlFile,
      console: true,
      output: config.testReportHtmlFile
    });`

In the output, I get node depreciation warnings like below
`(node:19980) [DEP0151] DeprecationWarning: Package C:\Projects\node-demo\node_modules\xunit-viewer\ has a "main" field set to "xunit-viewer", excluding the full filename and extension to the resolved file at "xunit-viewer.js", imported from C:\Projects\node-demo\src\test-runner.js.
 Automatic extension resolution of the "main" field is deprecated for ES modules.
(Use `node --trace-deprecation ` to show where the warning was created)`

Node version: v20.11.0
xunit-viewer version: 10.5.1

**Solution**
In the package.json, update `"main": "xunit-viewer"` to `"main": "xunit-viewer.js"` as ES6 expects files with extentions

**Comment by lukejpreston** [comment]
Thanks for this, this has been released now in v10.5.2
