### ISSUE TITLE
add support for uploading results files from remote ci instances

### ISSUE THREAD

**Issue by regevbr** [lukejpreston/xunit-viewer#16]
We are using the concourse ci for our pipelines and we want an easy way to see out test reports.
We think the best way is to start your server but allow it to be uploaded with test results...
Also adding support for grouping of test suits using url so we can give out a single url to the user thaqt iwll auto filter the restuls for the specific output

**Comment by lukejpreston** [comment]
this is more of a note to self

I am planning a re-write soon and intend to use react-router to do this

**Comment by lukejpreston** [comment]
have created a new issue for this
