### ISSUE TITLE
where case name is very long, it very break the card title wrapper.

### ISSUE THREAD

**Issue by BlazerYang** [lukejpreston/xunit-viewer#18]
i am using url as test case'name, sometimes it is so long that break the card title wrapper, so could you add word-break: break-all to .card-header-title.

another problem is that the error message in card-content is formatted with \n or whitespace, so could add to white-space:pre to .card-content.

txs a lot

**Comment by lukejpreston** [comment]
will look at first one in a moment but

update to v 5.1.0 now there is a toggle raw button on each test

I am changing the UI quite a bit and making the code much more efficient, in the meantime I have come to this solution instead of doing it on everything

**Comment by lukejpreston** [comment]
the text break word is now in v5.1.5
