### ISSUE TITLE
filter options not working?

### ISSUE THREAD

**Issue by benjaminwood** [lukejpreston/xunit-viewer#19]
I may be misunderstanding the documentation, but my expectation is that the following would filter out tests that passed. However, the result is that it shows tests that both passed and failed. I poked around in the code a bit and I haven't found where the filter options are used.

```bash
xunit-viewer --results=./units_2.xml --port=4000 --filter.test.types=pass
```

Thanks for your help!

**Comment by lukejpreston** [comment]
I have to have a look again myself. Those filters are primarily for terminal output and they may not work for html

**Comment by lukejpreston** [comment]
closing, assuming there was a miss understanding when the filter function is meant to be used

**Comment by BHSPitMonkey** [comment]
For what it's worth, I ran into the exact same issue/expectation and I agree that it seems like a defect. I'm trying to easily hide all the passing suites/tests from view without having to manually scroll and click each one to collapse them all, and nothing I pass to the `--filter` CLI options seems to make a difference.
