### ISSUE TITLE
HTML tags in error message can still break the page

### ISSUE THREAD

**Issue by barrettkingram** [lukejpreston/xunit-viewer#21]
Your recent changes are a step in the right direction but they don't fix all issues. This xml output still breaks the page:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuite tests="3" failures="1" time="0.0160106">
    <testcase name="has html" classname="HTML" time="0.00075">
        <error message="<b>BOO</b>" type="<i>ARGH</i>">
            Error found in line 77: &lt;script&gt;some garbage;&lt;/script&gt;
	</error>
    </testcase>
</testsuite>
```

I think you still need a command line option (perhaps --raw) that will set the Toggle Raw checkbox by default and avoid the dangerouslySetInnerHTML call completely. If you want, I can make a new PR for this.

**Comment by lukejpreston** [comment]
try 5.1.2 it is now raw by default

**Comment by lukejpreston** [comment]
oh i see the problem, I didn't notice the `&lt;` or `&gt;` will fix it now

**Comment by lukejpreston** [comment]
should be sorted in 5.1.3, I used your test data and that seems to work good

**Comment by barrettkingram** [comment]
Seems to work great now. Thanks!
