### ISSUE TITLE
CSV file into XUnit viewer

### ISSUE THREAD

**Issue by rseemaa** [lukejpreston/xunit-viewer#22]
Hi,
I have a CSV file with few data and I want the contents of the file to appear in the xunit-viewer report.
Any thoughts on how to achieve this ?
I am using selenium webdriverio..
Thanks

**Comment by rseemaa** [comment]
yes, I am using js...

**Comment by lukejpreston** [comment]
I have 2 thoughts

1. see if you can generate a junit/xunit report from your testing framework as selenium and webdriverio aren't testing frameworks. I used to use cucumberjs and found something which could generate junit reports which I then fed into this
2. convert your CSV into XML and feed that into this, you might need to create a script for this but you should be able to use any programming language to do this.

I don't think xunit-viewer will ever consume CSV or other formats other than xml in junit/xunit format. If you really wanted to you could use the React `XunitViewer` component, documented a bit in the README.md but I think this might be overkill and difficult to maintain as oppposed to the other two thoughts above.

I am going to close this unless you have other questions in which case you could re-open it if you want to.
