### ISSUE TITLE
Show test times

### ISSUE THREAD

**Issue by rhelmot** [lukejpreston/xunit-viewer#23]
there's a `time` attribute on all xunit `<testcase>` tags. This ought to appear in the output somehow. I'd be willing to work on this but I'm not a very good javascript programmer and I'd need some pointers for where to start.

**Comment by lukejpreston** [comment]
now in version 5.1.4

The old junit viewer I think used to have this. I have consciously decided not to put the units on the tests because I have seen some record ms and some record seconds and quite often neither record the unit but otherwise it will tell you the time

**Comment by rhelmot** [comment]
Fantastic, thank you!
