### ISSUE TITLE
For All Users of Xunit Viewer - 5.2.0 Preview Feedback Requests

### ISSUE THREAD

**Issue by lukejpreston** [lukejpreston/xunit-viewer#24]
I am currently working on 5.2.0 and have decided to redesign the interface. Before I start to implement the following image I thought I might ass the open source community what they thought of the following design.

* This is still fairly rough, padding and sizing in the image isn't correct but close enough for me to start developing
* I am currently designing my own icons instead of using font awesome but they should be similar
* Inspired by material design so expect better/more animations
* **new feature** of viewing/editing and inserting XML into the view should be coming in 5.2.0
* **new feature** of React Router in order to store filter paramters in the URL
* *desire* to create an electron app, you won't have to use command line

![xunit-viewer-5 2 0](https://user-images.githubusercontent.com/4129128/39419202-b5df00ba-4c56-11e8-8ec1-cdb9c485f17b.png)

**Comment by barrettkingram** [comment]
Looks good. I'm most excited about being able to pass filter parameters in the URL. Right now, I inject a script into the html that clicks the hide buttons for the success group upon opening the page. We have over 5000 tests so we don't care to see all the passing tests and it's a minor inconvenience having to choose to hide them each time. Other than that my only concern is that the page continues to work well with a large amount of test data. No complaints right now, but if you're going to be changing up a lot of things it would be nice if you tested with a big data set. Let me know if I can help.

**Comment by lukejpreston** [comment]
going to start work on this soon, assuming no one has any other feedback @barrettkingram if you can generate large data that would be great.I will create a new issue. Might be a good idea to randomly generate data for tests
