### ISSUE TITLE
False failure reported

### ISSUE THREAD

**Issue by rlichszteld-mdsol** [lukejpreston/xunit-viewer#3]
First of all, thanks for the great tool!

I have the following test case:

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="TestSuite" timestamp="2017-04-26T11:04:17" time="3.478" tests="0" failures="0" errors="0" skipped="0">
    <properties>
      <property name="specId" value="8bd15b60c2e4427bebe70fb618a717f4"/>
      <property name="suiteName" value="Create Action"/>
      <property name="capabilities" value="phantomjs"/>
    </properties>
  </testsuite>
  <testsuite name="release" timestamp="2017-04-26T11:04:17" time="3.478" tests="2" failures="0" errors="0" skipped="0">
    <properties>
      <property name="specId" value="8bd15b60c2e4427bebe70fb618a717f4"/>
      <property name="suiteName" value="@release"/>
      <property name="capabilities" value="phantomjs"/>
    </properties>
    <testcase classname="phantomjs.@release" name="testName_1" time="2.079">
    </testcase>
    <testcase classname="phantomjs.@release" name="testName_2" time="1.399">
    </testcase>
  </testsuite>
</testsuites>
```

that was created from the test suite:

```
describe('TestSuite', () => {
  context('@release', () => {
    it('testName_1', () => {
    })
   ....
})
```

The problem is in generated report `TestSuite` is reported as failing, even when it's not (in fact it is just a container for the actual `release` sub-suite):

![screen shot 2017-04-26 at 11 24 28](https://cloud.githubusercontent.com/assets/1628445/25430074/2c7f344e-2a73-11e7-96ec-0a0815b980ae.png)

**Comment by mfurtado-mdsol** [comment]
I see the same issue in couple of our projects where `xunit-viewer` behaves same.

**Comment by lukejpreston** [comment]
This should be fixed in version 5.0.3

<img width="947" alt="screenshot 2017-05-18 13 38 07" src="https://cloud.githubusercontent.com/assets/4129128/26202418/4be61880-3bcf-11e7-958e-eb84f6a70856.png">

**Comment by mfurtado-mdsol** [comment]
Thanks @lukejpreston

**Comment by rlichszteld-mdsol** [comment]
Thanks a lot @lukejpreston
