### ISSUE TITLE
component-ise

### ISSUE THREAD

**Issue by lukejpreston** [lukejpreston/xunit-viewer#32]
should be able to actually use as React components so as to be able to embed into other websites and applications

**Comment by luispollo** [comment]
I see this has been closed, but the README says "not available" under the "Usage, React" heading. I've been trying to get the `App` component to work in a test React app, but struggling as I'm not super familiar with React, etc. Would love to help in any way I can to get it to a working state, if you could give me some pointers.

**Comment by lukejpreston** [comment]
There would be a bunch of work with things like babel which would transform the jsx into something that can be consumed by other apps.

Most of the components are in this folder https://github.com/lukejpreston/xunit-viewer/tree/master/src/app and it might need splitting up so that each file can be exported and used in isolation.

I closed this because it seemed like quite a bit of work and I wasn't sure what the benefit would be. I would be interested in your use-case

**Comment by lukejpreston** [comment]
Reopening to keep track of this convo but might turn it into a new separate issue

**Comment by luispollo** [comment]
Hi @lukejpreston! Thanks for the feedback. 

> There would be a bunch of work with things like babel which would transform the jsx into something that can be consumed by other apps.

Yep. I found out the hard way. 🙂 The good news is that I got all the way to the point where I can build just the stuff in `src/app` as an NPM package with webpack and babel. It was a nice crash course on the tooling. 

> I closed this because it seemed like quite a bit of work and I wasn't sure what the benefit would be. I would be interested in your use-case

Our use case is in [Spinnaker](https://github.com/spinnaker), more specifically in Managed Delivery, which is a new set of features for continuous delivery. One of the features we recently rolled out is called "verifications" -- the ability to run automated tests against a live deployed environment. Most folks at Netflix use test tools that can output an xunit report, and that's how I ended up finding your tool. My idea was to allow Spinnaker users to visualize their test reports within our UI, which happens to be built on React. 

Hope that helps! I'd be happy to push my WIP changes to my fork so you can see what I've done so far, and/or provide details on what failed when I tried to use the exported component.
