### ISSUE TITLE
Whitespace conservation in code areas [really simple QoL fix]

### ISSUE THREAD

**Issue by EndlessDex** [lukejpreston/xunit-viewer#36]
Please add `white-space: pre-wrap` to the code style in bulma.css

Without this, code displayed in failed test windows has no newlines or tabs. (see below)
![image](https://user-images.githubusercontent.com/17400677/40549632-fb9660cc-6005-11e8-8904-9b6e0147fde1.png)

After modifying the style-sheet myself it looks like this:
![image](https://user-images.githubusercontent.com/17400677/40549767-56107ba0-6006-11e8-85cc-f69136a76c14.png)

![image](https://user-images.githubusercontent.com/17400677/40549700-2dfd5732-6006-11e8-8502-77dee95fcc27.png)

**Comment by lukejpreston** [comment]
managed to create one and if you update to 5.1.6 the fix is there
