### ISSUE TITLE
License

### ISSUE THREAD

**Issue by JesseChezenko-AI** [lukejpreston/xunit-viewer#37]
Thanks for your work on this project.

Would you be open to adding a license to this project?  https://choosealicense.com/

**Comment by lukejpreston** [comment]
Sure, I have picked MIT from those 3. When I upgrade to version 5 (should be soon) then you will see the licence in the repo. Are there any shiny GitHub badges for this?

**Comment by lukejpreston** [comment]
Currently the package.json says it is an ISC licence

**Comment by JesseChezenko-AI** [comment]
Ah, I overlooked that. That works for me.

Thanks for the quick reply.
