### ISSUE TITLE
yellow color codes

### ISSUE THREAD

**Issue by rseemaa** [lukejpreston/xunit-viewer#37]
What does the yellow color code mean ? I understand red is failed and green is passed.. 
I am using the same assert statement (assert.equal) in selenium webdriverIO. But some testcase in the report have yellow color versus a few having red color.
Can you someone help me understand this ?

**Comment by lukejpreston** [comment]
red is fail
green is pass
blue is unknown
grey is skipped
yellow is error

typically error means that your tests failed, not an assertion failure

**Comment by lukejpreston** [comment]
going to close, feel free to add more comments and reopen if you want more clarification. Unknown means that the test has a `type="something I don't know"`
