### ISSUE TITLE
SyntaxError: Unexpected identifier on docker container

### ISSUE THREAD

**Issue by lhimo** [lukejpreston/xunit-viewer#45]
Executing xunit-viewer on a docker container I get the error:

```
/usr/local/lib/node_modules/xunit-viewer/bin/xunit-viewer:3
let options = require('../cli/resolve-argv')()
    ^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

How can I troubleshoot?

**Comment by lukejpreston** [comment]
What version of node is the container running?

**Comment by lhimo** [comment]
v0.10.29

**Comment by lukejpreston** [comment]
That's an old version.

Here are the node releases https://github.com/nodejs/Release

v0.10 went end of life 2016-10-31 and the current LTS is v10 so you should upgrade all your code to v10 and above ideally. I believe Xunit Viewer will work on v6 and above but I am not sure, maybe v8 and above but I won't be supporting anything less than current LTS even if it does run on an older version.

If you want some advice on Docker containers I might be able to help, but I think Google probably has more answers than me.
