### ISSUE TITLE
xunit-viewer not found when using within Nodejs module

### ISSUE THREAD

**Issue by randygschmidt** [lukejpreston/xunit-viewer#49]
Using the following in VisualStudio Code running on Windows 10 xunit-version 5.1.10:

const XunitViewer = require('xunit-viewer')

const result = XunitViewer({
    results: './newman',
    output: 'Collection_results.html',
    title: 'Data Distribution',
})

I get the following error using lint:
Could not find a declaration file for module 'xunit-viewer'. 'c:/Projects/Data_Distribution/API_Testing/node_modules/xunit-viewer/xunit-viewer.js' implicitly has an 'any' type.
  Try `npm install @types/xunit-viewer` if it exists or add a new declaration (.d.ts) file containing `declare module 'xunit-viewer';

and I get the following error  when executing:
b'C:\\Projects\\Data_Distribution\\API_Testing\\generateReport.js:3
const result = XunitViewer({
               ^\r\n\r\nTypeError: XunitViewer is not a function\r\n    at Object.<anonymous> (C:\\Projects\\Data_Distribution\\API_Testing\\generateReport.js:3:16)\r\n    at Module._compile (internal/modules/cjs/loader.js:689:30)\r\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)\r\n    at Module.load (internal/modules/cjs/loader.js:599:32)\r\n    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)\r\n    at Function.Module._load (internal/modules/cjs/loader.js:530:3)\r\n    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)\r\n    at startup (internal/bootstrap/node.js:283:19)\r\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)\r\n'

If I run from command line then it generates html file.  I have put xunit-viewer in package.json as well as installed using npm i -D xunit-viewer

I have also tried const XunitViewer = require('xunit-viewer/cli') and get the same results.

**Comment by lukejpreston** [comment]
I'm not too sure what is going on exactly there.

What do you mean you are running it in `VisualStudio Code`?

Here are the steps I think you need to possible do (note the README might be wrong)

```sh
mkdir API_Testing
cd API_Testing
npm init -y
npm i -D xunit-viewer
touch generateReport.js
```

`generateReport.js` should look like

```js
const XunitViewer = require('xunit-viewer/cli')

XunitViewer({
    results: './newman',
    output: 'Collection_results.html',
    title: 'Data Distribution',
})
```

then run

```js
node generateReport.js
```

That works for me. When I use VSCode I  just have the `generateReport.js` open and press `F5` and it works just the same.

I am using node `v10.15.3` (which is lts) and npm `v6.9.0`

The only difference is that I am using Linux and not Windows, I doubt that is the problem.

I would suggest just doing a quick mini project and do the steps I have done above.

I haven't tried using Xunit Viewer using typescript, which I wonder if that is the issue. Let me know whether you are using typescript and I will install it and see whether I get the same error.

**Comment by randygschmidt** [comment]
That was exactly what I had done prior to reporting the problem. I had tried it both with and without the /cli (which is not shown in the readme but was shown in another message)

Pressing F5 yielded the error I reported.

I use the newman library module and it  uses typescript and works while xunit-viewer does not. Use typescript and fails.

My environment to develop and run is Windows 10. I have not spun up a Linux VM to see if it works under Linux. I believe that it is the environment that is causing the issue and how npm install the library/module.

Thanks Randy

**Comment by lukejpreston** [comment]
I'm not too familiar with typescript, I would have to see about running this code using typescript. As I said, VSCode worked for me with the code I shared with you, but it was built using node, not typescript. I will see if typescript reproduces the same error and get back to you.

**Comment by randygschmidt** [comment]
Since I have no typescript libraries loaded for it and it appears that non are available through npm … this test shouldn’t be necessary.

If you have typescript libraries then I can load them and see if the problem goes away.

I have also tried running it from command line node reportGenerator.js and get the same failure … it does not like running on Windows.

Thanks

**Comment by lukejpreston** [comment]
I don't have a windows machine, I will also spin up a windows VM and see if I get the same error

**Comment by randygschmidt** [comment]
Running from command line using require(‘xunit-viewer/cli’) works … and now using with the application …

I had to install typescript (npm I -g typescript) to make it work … not sure why

You have created an amazing tool … I would love to work on it if you need additional resources.

Have a great holiday weekend

Thanks for the quick response

Randy

**Comment by randygschmidt** [comment]
Missing module (typescript) required when running in Windows 10.
