### ISSUE TITLE
Css Generation Issue

### ISSUE THREAD

**Issue by hirokiht** [lukejpreston/xunit-viewer#57]
Since upgraded from 5.1.11 to 5.1.13, the generated css on my site is broken, here's a snippet
`.hero {
 background-image:linear-gradient(141deg,#2C3E50 0,color(#2C3E50 tint(5%)) 71%,color(#2C3E50 tint(10%)) 100%);
 &-head {
  height:49px;
  & .title {
   color:#fff;
   line-height:49px
  }`
My guess is it has something to with postcss processing, but I have not been able to narrow it down.
Packages installed by npm:
`-- xunit-viewer@5.1.13 
  +-- @babel/preset-env@7.7.1 
  | +-- @babel/helper-module-imports@7.7.0 
  | +-- @babel/helper-plugin-utils@7.0.0 
  | +-- @babel/plugin-proposal-async-generator-functions@7.7.0 
  | | `-- @babel/helper-remap-async-to-generator@7.7.0 
  | |   `-- @babel/helper-wrap-function@7.7.0 
  | +-- @babel/plugin-proposal-dynamic-import@7.7.0 
  | +-- @babel/plugin-proposal-json-strings@7.2.0 
  | +-- @babel/plugin-proposal-object-rest-spread@7.6.2 
  | +-- @babel/plugin-proposal-optional-catch-binding@7.2.0 
  | +-- @babel/plugin-proposal-unicode-property-regex@7.7.0 
  | | `-- @babel/helper-create-regexp-features-plugin@7.7.2 
  | |   `-- regexpu-core@4.6.0 
  | |     +-- regenerate@1.4.0 
  | |     +-- regenerate-unicode-properties@8.1.0 
  | |     +-- regjsgen@0.5.1 
  | |     +-- regjsparser@0.6.0 
  | |     | `-- jsesc@0.5.0 
  | |     +-- unicode-match-property-ecmascript@1.0.4 
  | |     | +-- unicode-canonical-property-names-ecmascript@1.0.4 
  | |     | `-- unicode-property-aliases-ecmascript@1.0.5 
  | |     `-- unicode-match-property-value-ecmascript@1.1.0 
  | +-- @babel/plugin-syntax-async-generators@7.2.0 
  | +-- @babel/plugin-syntax-dynamic-import@7.2.0 
  | +-- @babel/plugin-syntax-json-strings@7.2.0 
  | +-- @babel/plugin-syntax-object-rest-spread@7.2.0 
  | +-- @babel/plugin-syntax-optional-catch-binding@7.2.0 
  | +-- @babel/plugin-syntax-top-level-await@7.7.0 
  | +-- @babel/plugin-transform-arrow-functions@7.2.0 
  | +-- @babel/plugin-transform-async-to-generator@7.7.0 
  | +-- @babel/plugin-transform-block-scoped-functions@7.2.0 
  | +-- @babel/plugin-transform-block-scoping@7.6.3 
  | +-- @babel/plugin-transform-classes@7.7.0 
  | | +-- @babel/helper-annotate-as-pure@7.7.0 
  | | +-- @babel/helper-define-map@7.7.0 
  | | +-- @babel/helper-function-name@7.7.0 
  | | +-- @babel/helper-optimise-call-expression@7.7.0 
  | | +-- @babel/helper-replace-supers@7.7.0 
  | | | `-- @babel/helper-member-expression-to-functions@7.7.0 
  | | +-- @babel/helper-split-export-declaration@7.7.0 
  | | `-- globals@11.12.0 
  | +-- @babel/plugin-transform-computed-properties@7.2.0 
  | +-- @babel/plugin-transform-destructuring@7.6.0 
  | +-- @babel/plugin-transform-dotall-regex@7.7.0 
  | +-- @babel/plugin-transform-duplicate-keys@7.5.0 
  | +-- @babel/plugin-transform-exponentiation-operator@7.2.0 
  | | `-- @babel/helper-builder-binary-assignment-operator-visitor@7.7.0 
  | |   `-- @babel/helper-explode-assignable-expression@7.7.0 
  | +-- @babel/plugin-transform-for-of@7.4.4 
  | +-- @babel/plugin-transform-function-name@7.7.0 
  | +-- @babel/plugin-transform-literals@7.2.0 
  | +-- @babel/plugin-transform-member-expression-literals@7.2.0 
  | +-- @babel/plugin-transform-modules-amd@7.5.0 
  | | `-- @babel/helper-module-transforms@7.7.0 
  | +-- @babel/plugin-transform-modules-commonjs@7.7.0 
  | | `-- @babel/helper-simple-access@7.7.0 
  | +-- @babel/plugin-transform-modules-systemjs@7.7.0 
  | | `-- @babel/helper-hoist-variables@7.7.0 
  | +-- @babel/plugin-transform-modules-umd@7.7.0 
  | +-- @babel/plugin-transform-named-capturing-groups-regex@7.7.0 
  | +-- @babel/plugin-transform-new-target@7.4.4 
  | +-- @babel/plugin-transform-object-super@7.5.5 
  | +-- @babel/plugin-transform-parameters@7.4.4 
  | | +-- @babel/helper-call-delegate@7.7.0 
  | | `-- @babel/helper-get-function-arity@7.7.0 
  | +-- @babel/plugin-transform-property-literals@7.2.0 
  | +-- @babel/plugin-transform-regenerator@7.7.0 
  | | `-- regenerator-transform@0.14.1 
  | +-- @babel/plugin-transform-reserved-words@7.2.0 
  | +-- @babel/plugin-transform-shorthand-properties@7.2.0 
  | +-- @babel/plugin-transform-spread@7.6.2 
  | +-- @babel/plugin-transform-sticky-regex@7.2.0 
  | | `-- @babel/helper-regex@7.5.5 
  | +-- @babel/plugin-transform-template-literals@7.4.4 
  | +-- @babel/plugin-transform-typeof-symbol@7.2.0 
  | +-- @babel/plugin-transform-unicode-regex@7.7.0 
  | +-- @babel/types@7.7.2 
  | | +-- esutils@2.0.3 
  | | `-- to-fast-properties@2.0.0 
  | +-- browserslist@4.7.2 
  | | +-- electron-to-chromium@1.3.306 
  | | `-- node-releases@1.1.40 
  | |   `-- semver@6.3.0 
  | +-- core-js-compat@3.4.1 
  | | `-- semver@6.3.0 
  | +-- invariant@2.2.4 
  | +-- js-levenshtein@1.1.6 
  | `-- semver@5.7.1 
  +-- @babel/preset-react@7.7.0 
  | +-- @babel/plugin-transform-react-display-name@7.2.0 
  | +-- @babel/plugin-transform-react-jsx@7.7.0 
  | | +-- @babel/helper-builder-react-jsx@7.7.0 
  | | `-- @babel/plugin-syntax-jsx@7.2.0 
  | +-- @babel/plugin-transform-react-jsx-self@7.2.0 
  | `-- @babel/plugin-transform-react-jsx-source@7.5.0 
  +-- babel-core@6.26.3 
  | +-- babel-code-frame@6.26.0 
  | | +-- chalk@1.1.3 
  | | | +-- ansi-styles@2.2.1 
  | | | +-- has-ansi@2.0.0 
  | | | | `-- ansi-regex@2.1.1 
  | | | +-- strip-ansi@3.0.1 
  | | | `-- supports-color@2.0.0 
  | | `-- js-tokens@3.0.2 
  | +-- babel-generator@6.26.1 
  | | +-- detect-indent@4.0.0 
  | | | `-- repeating@2.0.1 
  | | |   `-- is-finite@1.0.2 
  | | |     `-- number-is-nan@1.0.1 
  | | +-- jsesc@1.3.0 
  | | `-- trim-right@1.0.1 
  | +-- babel-helpers@6.24.1 
  | +-- babel-messages@6.23.0 
  | +-- babel-register@6.26.0 
  | | +-- core-js@2.6.10 
  | | +-- home-or-tmp@2.0.0 
  | | | +-- os-homedir@1.0.2 
  | | | `-- os-tmpdir@1.0.2 
  | | `-- source-map-support@0.4.18 
  | +-- babel-runtime@6.26.0 
  | | `-- regenerator-runtime@0.11.1 
  | +-- babel-template@6.26.0 
  | +-- babel-traverse@6.26.0 
  | | +-- debug@2.6.9 
  | | | `-- ms@2.0.0 
  | | `-- globals@9.18.0 
  | +-- babel-types@6.26.0 
  | | `-- to-fast-properties@1.0.3 
  | +-- babylon@6.18.0 
  | +-- convert-source-map@1.7.0 
  | +-- debug@2.6.9 
  | | `-- ms@2.0.0 
  | +-- json5@0.5.1 
  | +-- lodash@4.17.15 
  | +-- minimatch@3.0.4 
  | | `-- brace-expansion@1.1.11 
  | |   `-- concat-map@0.0.1 
  | +-- path-is-absolute@1.0.1 
  | +-- private@0.1.8 
  | +-- slash@1.0.0 
  | `-- source-map@0.5.7 
  +-- babel-preset-react-app@9.0.2 
  | +-- @babel/core@7.6.0 
  | | +-- @babel/code-frame@7.5.5 
  | | | `-- @babel/highlight@7.5.0 
  | | +-- @babel/generator@7.7.2 
  | | | `-- jsesc@2.5.2 
  | | +-- @babel/helpers@7.7.0 
  | | +-- @babel/parser@7.7.3 
  | | +-- @babel/template@7.7.0 
  | | +-- @babel/traverse@7.7.2 
  | | `-- json5@2.1.1 
  | |   `-- minimist@1.2.0 
  | +-- @babel/plugin-proposal-class-properties@7.5.5 
  | | `-- @babel/helper-create-class-features-plugin@7.7.0 
  | +-- @babel/plugin-proposal-decorators@7.6.0 
  | | `-- @babel/plugin-syntax-decorators@7.2.0 
  | +-- @babel/plugin-proposal-object-rest-spread@7.5.5 
  | +-- @babel/plugin-transform-flow-strip-types@7.4.4 
  | | `-- @babel/plugin-syntax-flow@7.7.0 
  | +-- @babel/plugin-transform-runtime@7.6.0 
  | +-- @babel/preset-env@7.6.0 
  | +-- @babel/preset-react@7.0.0 
  | +-- @babel/preset-typescript@7.6.0 
  | | `-- @babel/plugin-transform-typescript@7.7.2 
  | |   `-- @babel/plugin-syntax-typescript@7.3.3 
  | +-- @babel/runtime@7.6.0 
  | | `-- regenerator-runtime@0.13.3 
  | +-- babel-plugin-dynamic-import-node@2.3.0 
  | | `-- object.assign@4.1.0 
  | |   +-- define-properties@1.1.3 
  | |   +-- has-symbols@1.0.1 
  | |   `-- object-keys@1.1.1 
  | +-- babel-plugin-macros@2.6.1 
  | | `-- cosmiconfig@5.2.1 
  | |   +-- import-fresh@2.0.0 
  | |   | +-- caller-path@2.0.0 
  | |   | | `-- caller-callsite@2.0.0 
  | |   | |   `-- callsites@2.0.0 
  | |   | `-- resolve-from@3.0.0 
  | |   +-- is-directory@0.3.1 
  | |   +-- js-yaml@3.13.1 
  | |   | +-- argparse@1.0.10 
  | |   | | `-- sprintf-js@1.0.3 
  | |   | `-- esprima@4.0.1 
  | |   `-- parse-json@4.0.0 
  | |     +-- error-ex@1.3.2 
  | |     | `-- is-arrayish@0.2.1 
  | |     `-- json-parse-better-errors@1.0.2 
  | `-- babel-plugin-transform-react-remove-prop-types@0.4.24 
  +-- babelify@10.0.0 
  +-- browserify@16.5.0 
  | +-- assert@1.5.0 
  | | `-- util@0.10.3 
  | |   `-- inherits@2.0.1 
  | +-- browser-pack@6.1.0 
  | | +-- combine-source-map@0.8.0 
  | | | +-- convert-source-map@1.1.3 
  | | | +-- inline-source-map@0.6.2 
  | | | `-- lodash.memoize@3.0.4 
  | | `-- umd@3.0.3 
  | +-- browser-resolve@1.11.3 
  | | `-- resolve@1.1.7 
  | +-- browserify-zlib@0.2.0 
  | | `-- pako@1.0.10 
  | +-- buffer@5.4.3 
  | | +-- base64-js@1.3.1 
  | | `-- ieee754@1.1.13 
  | +-- cached-path-relative@1.0.2 
  | +-- concat-stream@1.6.2 
  | | +-- buffer-from@1.1.1 
  | | `-- typedarray@0.0.6 
  | +-- console-browserify@1.2.0 
  | +-- constants-browserify@1.0.0 
  | +-- crypto-browserify@3.12.0 
  | | +-- browserify-cipher@1.0.1 
  | | | +-- browserify-aes@1.2.0 
  | | | | `-- buffer-xor@1.0.3 
  | | | +-- browserify-des@1.0.2 
  | | | | `-- des.js@1.0.1 
  | | | `-- evp_bytestokey@1.0.3 
  | | +-- browserify-sign@4.0.4 
  | | | +-- bn.js@4.11.8 
  | | | +-- browserify-rsa@4.0.1 
  | | | +-- elliptic@6.5.1 
  | | | | +-- brorand@1.1.0 
  | | | | +-- hash.js@1.1.7 
  | | | | +-- hmac-drbg@1.0.1 
  | | | | +-- minimalistic-assert@1.0.1 
  | | | | `-- minimalistic-crypto-utils@1.0.1 
  | | | `-- parse-asn1@5.1.5 
  | | |   `-- asn1.js@4.10.1 
  | | +-- create-ecdh@4.0.3 
  | | +-- create-hash@1.2.0 
  | | | +-- cipher-base@1.0.4 
  | | | +-- md5.js@1.3.5 
  | | | | `-- hash-base@3.0.4 
  | | | `-- ripemd160@2.0.2 
  | | +-- create-hmac@1.1.7 
  | | +-- diffie-hellman@5.0.3 
  | | | `-- miller-rabin@4.0.1 
  | | +-- pbkdf2@3.0.17 
  | | +-- public-encrypt@4.0.3 
  | | +-- randombytes@2.1.0 
  | | `-- randomfill@1.0.4 
  | +-- defined@1.0.0 
  | +-- deps-sort@2.0.1 
  | | `-- shasum-object@1.0.0 
  | |   `-- fast-safe-stringify@2.0.7 
  | +-- domain-browser@1.2.0 
  | +-- duplexer2@0.1.4 
  | +-- events@2.1.0 
  | +-- glob@7.1.6 
  | | +-- fs.realpath@1.0.0 
  | | +-- inflight@1.0.6 
  | | | `-- wrappy@1.0.2 
  | | `-- once@1.4.0 
  | +-- has@1.0.3 
  | | `-- function-bind@1.1.1 
  | +-- htmlescape@1.1.1 
  | +-- https-browserify@1.0.0 
  | +-- inherits@2.0.4 
  | +-- insert-module-globals@7.2.0 
  | | +-- acorn-node@1.8.2 
  | | | +-- acorn@7.1.0 
  | | | `-- acorn-walk@7.0.0 
  | | +-- is-buffer@1.1.6 
  | | `-- undeclared-identifiers@1.1.3 
  | |   +-- dash-ast@1.0.0 
  | |   +-- get-assigned-identifiers@1.2.0 
  | |   `-- simple-concat@1.0.0 
  | +-- JSONStream@1.3.5 
  | | +-- jsonparse@1.3.1 
  | | `-- through@2.3.8 
  | +-- labeled-stream-splicer@2.0.2 
  | | `-- stream-splicer@2.0.1 
  | +-- mkdirp@0.5.1 
  | | `-- minimist@0.0.8 
  | +-- module-deps@6.2.1 
  | | +-- detective@5.2.0 
  | | | `-- minimist@1.2.0 
  | | `-- stream-combiner2@1.1.1 
  | +-- os-browserify@0.3.0 
  | +-- parents@1.0.1 
  | | `-- path-platform@0.11.15 
  | +-- path-browserify@0.0.1 
  | +-- process@0.11.10 
  | +-- punycode@1.4.1 
  | +-- querystring-es3@0.2.1 
  | +-- read-only-stream@2.0.0 
  | +-- readable-stream@2.3.6 
  | | +-- core-util-is@1.0.2 
  | | +-- isarray@1.0.0 
  | | +-- process-nextick-args@2.0.1 
  | | +-- string_decoder@1.1.1 
  | | `-- util-deprecate@1.0.2 
  | +-- resolve@1.12.0 
  | | `-- path-parse@1.0.6 
  | +-- shasum@1.0.2 
  | | +-- json-stable-stringify@0.0.1 
  | | | `-- jsonify@0.0.0 
  | | `-- sha.js@2.4.11 
  | +-- shell-quote@1.7.2 
  | +-- stream-browserify@2.0.2 
  | +-- stream-http@3.1.0 
  | | +-- builtin-status-codes@3.0.0 
  | | `-- readable-stream@3.4.0 
  | +-- string_decoder@1.3.0 
  | | `-- safe-buffer@5.2.0 
  | +-- subarg@1.0.0 
  | | `-- minimist@1.2.0 
  | +-- syntax-error@1.4.0 
  | +-- through2@2.0.5 
  | +-- timers-browserify@1.4.2 
  | +-- tty-browserify@0.0.1 
  | +-- url@0.11.0 
  | | +-- punycode@1.3.2 
  | | `-- querystring@0.2.0 
  | +-- util@0.10.4 
  | | `-- inherits@2.0.3 
  | +-- vm-browserify@1.1.2 
  | `-- xtend@4.0.2 
  +-- bulma@0.7.5 
  +-- chalk@2.4.2 
  | +-- ansi-styles@3.2.1 
  | | `-- color-convert@1.9.3 
  | |   `-- color-name@1.1.3 
  | +-- escape-string-regexp@1.0.5 
  | `-- supports-color@5.5.0 
  |   `-- has-flag@3.0.0 
  +-- clone@2.1.2 
  +-- detect-port@1.3.0 
  | +-- address@1.1.2 
  | `-- debug@2.6.9 
  |   `-- ms@2.0.0 
  +-- express@4.17.1 
  | +-- accepts@1.3.7 
  | | +-- mime-types@2.1.25 
  | | | `-- mime-db@1.42.0 
  | | `-- negotiator@0.6.2 
  | +-- array-flatten@1.1.1 
  | +-- body-parser@1.19.0 
  | | +-- bytes@3.1.0 
  | | +-- debug@2.6.9 
  | | | `-- ms@2.0.0 
  | | +-- http-errors@1.7.2 
  | | | +-- inherits@2.0.3 
  | | | `-- toidentifier@1.0.0 
  | | +-- iconv-lite@0.4.24 
  | | | `-- safer-buffer@2.1.2 
  | | `-- raw-body@2.4.0 
  | +-- content-disposition@0.5.3 
  | +-- content-type@1.0.4 
  | +-- cookie@0.4.0 
  | +-- cookie-signature@1.0.6 
  | +-- debug@2.6.9 
  | | `-- ms@2.0.0 
  | +-- depd@1.1.2 
  | +-- encodeurl@1.0.2 
  | +-- escape-html@1.0.3 
  | +-- etag@1.8.1 
  | +-- finalhandler@1.1.2 
  | | +-- debug@2.6.9 
  | | | `-- ms@2.0.0 
  | | `-- unpipe@1.0.0 
  | +-- fresh@0.5.2 
  | +-- merge-descriptors@1.0.1 
  | +-- methods@1.1.2 
  | +-- on-finished@2.3.0 
  | | `-- ee-first@1.1.1 
  | +-- parseurl@1.3.3 
  | +-- path-to-regexp@0.1.7 
  | +-- proxy-addr@2.0.5 
  | | +-- forwarded@0.1.2 
  | | `-- ipaddr.js@1.9.0 
  | +-- qs@6.7.0 
  | +-- range-parser@1.2.1 
  | +-- safe-buffer@5.1.2 
  | +-- send@0.17.1 
  | | +-- debug@2.6.9 
  | | | `-- ms@2.0.0 
  | | +-- destroy@1.0.4 
  | | +-- mime@1.6.0 
  | | `-- ms@2.1.1 
  | +-- serve-static@1.14.1 
  | +-- setprototypeof@1.1.1 
  | +-- statuses@1.5.0 
  | +-- type-is@1.6.18 
  | | `-- media-typer@0.3.0 
  | +-- utils-merge@1.0.1 
  | `-- vary@1.1.2 
  +-- fs-extra@8.1.0 
  | +-- graceful-fs@4.2.3 
  | +-- jsonfile@4.0.0 
  | `-- universalify@0.1.2 
  +-- fuzzysearch@1.0.3 
  +-- mustache@3.1.0 
  +-- node-watch@0.6.3 
  +-- normalize.css@8.0.1 
  +-- postcss@7.0.21 
  | +-- source-map@0.6.1 
  | `-- supports-color@6.1.0 
  +-- postcss-preset-env@6.7.0 
  | +-- autoprefixer@9.7.1 
  | | +-- normalize-range@0.1.2 
  | | +-- num2fraction@1.2.2 
  | | `-- postcss-value-parser@4.0.2 
  | +-- caniuse-lite@1.0.30001010 
  | +-- css-blank-pseudo@0.1.4 
  | +-- css-has-pseudo@0.10.0 
  | | `-- postcss-selector-parser@5.0.0 
  | |   +-- cssesc@2.0.0 
  | |   +-- indexes-of@1.0.1 
  | |   `-- uniq@1.0.1 
  | +-- css-prefers-color-scheme@3.1.1 
  | +-- cssdb@4.4.0 
  | +-- postcss-attribute-case-insensitive@4.0.1 
  | +-- postcss-color-functional-notation@2.0.1 
  | | `-- postcss-values-parser@2.0.1 
  | |   `-- flatten@1.0.3 
  | +-- postcss-color-gray@5.0.0 
  | | `-- @csstools/convert-colors@1.4.0 
  | +-- postcss-color-hex-alpha@5.0.3 
  | +-- postcss-color-mod-function@3.0.3 
  | +-- postcss-color-rebeccapurple@4.0.1 
  | +-- postcss-custom-media@7.0.8 
  | +-- postcss-custom-properties@8.0.11 
  | +-- postcss-custom-selectors@5.1.2 
  | +-- postcss-dir-pseudo-class@5.0.0 
  | +-- postcss-double-position-gradients@1.0.0 
  | +-- postcss-env-function@2.0.2 
  | +-- postcss-focus-visible@4.0.0 
  | +-- postcss-focus-within@3.0.0 
  | +-- postcss-font-variant@4.0.0 
  | +-- postcss-gap-properties@2.0.0 
  | +-- postcss-image-set-function@3.0.1 
  | +-- postcss-initial@3.0.2 
  | | `-- lodash.template@4.5.0 
  | |   +-- lodash._reinterpolate@3.0.0 
  | |   `-- lodash.templatesettings@4.2.0 
  | +-- postcss-lab-function@2.0.1 
  | +-- postcss-logical@3.0.0 
  | +-- postcss-media-minmax@4.0.0 
  | +-- postcss-nesting@7.0.1 
  | +-- postcss-overflow-shorthand@2.0.0 
  | +-- postcss-page-break@2.0.0 
  | +-- postcss-place@4.0.1 
  | +-- postcss-pseudo-class-any-link@6.0.0 
  | +-- postcss-replace-overflow-wrap@3.0.0 
  | +-- postcss-selector-matches@4.0.0 
  | | `-- balanced-match@1.0.0 
  | `-- postcss-selector-not@4.0.0 
  +-- promise@8.0.3 
  | `-- asap@2.0.6 
  +-- react@16.12.0 
  | +-- loose-envify@1.4.0 
  | | `-- js-tokens@4.0.0 
  | +-- object-assign@4.1.1 
  | `-- prop-types@15.7.2 
  |   `-- react-is@16.12.0 
  +-- react-dom@16.12.0 
  | `-- scheduler@0.18.0 
  +-- recursive-readdir@2.2.2 
  +-- socket.io@2.3.0 
  | +-- debug@4.1.1 
  | | `-- ms@2.1.2 
  | +-- engine.io@3.4.0 
  | | +-- base64id@2.0.0 
  | | +-- cookie@0.3.1 
  | | +-- engine.io-parser@2.2.0 
  | | | +-- after@0.8.2 
  | | | +-- arraybuffer.slice@0.0.7 
  | | | `-- blob@0.0.5 
  | | `-- ws@7.2.0 
  | |   `-- async-limiter@1.0.1 
  | +-- has-binary2@1.0.3 
  | | `-- isarray@2.0.1 
  | +-- socket.io-adapter@1.1.1 
  | +-- socket.io-client@2.3.0 
  | | +-- backo2@1.0.2 
  | | +-- base64-arraybuffer@0.1.5 
  | | +-- component-bind@1.0.0 
  | | +-- component-emitter@1.2.1 
  | | +-- engine.io-client@3.4.0 
  | | | +-- component-inherit@0.0.3 
  | | | +-- ws@6.1.4 
  | | | +-- xmlhttprequest-ssl@1.5.5 
  | | | `-- yeast@0.1.2 
  | | +-- has-cors@1.1.0 
  | | +-- indexof@0.0.1 
  | | +-- object-component@0.0.3 
  | | +-- parseqs@0.0.5 
  | | | `-- better-assert@1.0.2 
  | | |   `-- callsite@1.0.0 
  | | +-- parseuri@0.0.5 
  | | +-- socket.io-parser@3.3.0 
  | | | +-- debug@3.1.0 
  | | | | `-- ms@2.0.0 
  | | | `-- isarray@2.0.1 
  | | `-- to-array@0.1.4 
  | `-- socket.io-parser@3.4.0 
  |   `-- isarray@2.0.1 
  +-- titlecase@1.1.3 
  +-- uglify-js@3.6.9 
  | +-- commander@2.20.3 
  | `-- source-map@0.6.1 
  +-- uglifycss@0.0.29 
  +-- uuid@3.3.3 
  `-- xml2js-parser@1.1.1 
    `-- sax@1.2.4 `

**Comment by lukejpreston** [comment]
out of curiosity, what browser are you running the output in?

**Comment by lukejpreston** [comment]
you are right that it is the plugin, the old one was throwing errors not allowing people to run the code any longer. I am looking into this

**Comment by lukejpreston** [comment]
I have a fix in version 5.2 it isn't as pretty as I used to have but I am working on v6 which looks much better and won't have these issues

let me know if the problem still persists
