### ISSUE TITLE
filter using react router

### ISSUE THREAD

**Issue by lukejpreston** [lukejpreston/xunit-viewer#59]

**Comment by zeburek** [comment]
@lukejpreston could you please open a WIP MR for this feature?
I have a couple suggessions for your current code, which would be quite near this feature

**Comment by lukejpreston** [comment]
I almost have something working, it is only a couple of lines long. What sort of suggestions did you have?

**Comment by zeburek** [comment]
Use React hooks + Context provider instead of dispatcher mecanism

It will simplify the code and will make it clear

**Comment by lukejpreston** [comment]
I don't think this issue should solve refactoring problems, but I love the enthusiasm! I have a bunch of cleaning jobs I would like to do which include looking at what you have suggested here

**Comment by tbourrelovh** [comment]
Hello :slightly_smiling_face: 
Any news on this feature ?

**Comment by lukejpreston** [comment]
This is doable now https://github.com/lukejpreston/xunit-viewer/releases/tag/v10.0.0
It only filters by test status for now, once the cli filtering has been fixed the two can be aligned
