### ISSUE TITLE
Google test support ?

### ISSUE THREAD

**Issue by avk2** [lukejpreston/xunit-viewer#6]
https://github.com/google/googletest/blob/master/googletest/docs/AdvancedGuide.md#generating-an-xml-report 

It seems to be able to parse the googletest report but the result is wrong.

![screenshot_2017-09-04_09-56-34](https://user-images.githubusercontent.com/4255121/30016955-8b1af09c-9157-11e7-8c48-94e9a15bee75.png)

The '?' should be success and failures messages aren't shown properly. 

This is the report: https://pastebin.com/2Kvtw2eK

Has easy solution?

**Comment by lukejpreston** [comment]
looks like the test's have `status="run"` which I hadn't come across before hence the `?` I don't know googletest is `run` equiv. to `pass`?

**Comment by lukejpreston** [comment]
also you have multiple failures in you failing test, which is a scenario I hadn't considered before and am surprised it picks the first failure. I will use this test case and look into getting both issues resolved

**Comment by avk2** [comment]
I guess. I changed it to `pass` and now is fine. 

Yes, on one test I have multiple asserts, so the the test success if all of them passes and fails if one fails.
