### ISSUE TITLE
Recursivity and file patterns

### ISSUE THREAD

**Issue by thoni56** [lukejpreston/xunit-viewer#61]
I'm creating a visual result from a bunch of tests in a CI flow. It would be nice if `xunit-viewer` could recurse and look for filename patterns to combine into a single index.html.

E.g.

    xunit-viewer --recurse tests --pattern TEST*.xml --output index.html

**Comment by lukejpreston** [comment]
I think it already does this but it ignores files and reads the rest for example, `xunit-viewer -r tests -i pattern1, pattern2 -o index.html`

Do you mean you want the opposite of this so, for example, you would like `xunit-viewer -r tests/TEST*.xml -o index.html`

I think this would be easier to code, but does it meet your requirements?

**Comment by thoni56** [comment]
I guess what *I* think would be easier use would to indicate which file patterns to include, rather than ignore. My result files are placed in the test directories, so there are a large number of other types of files there too. But they are also dispersed through the whole directory hierarchy, so recursion is still needed, not just a pattern in a single directory. So I guess that just giving a path pattern, as I read your suggestion, would not suffice.

So I would like to see an "include" pattern option, rather than an "ignore" (which could be read as "exclude").

Of course, I could do a compilation of the files separately before running `xunit-viewer` but it would be handy to not having to do that.

**Comment by lukejpreston** [comment]
It should be recursive by default

I just looked at the code and noticed it doesn't filter XML files which I will change now, once I deploy it I will let you know and then we can see how far off it is to having something which works for you

**Comment by lukejpreston** [comment]
Try version `6.0.10` you should be able to do `xunit-viewer -r tests -o index.html` and it will ignore anything but xml files and it is recursive by default

Once you have done that then we can work out how the includes should work

**Comment by thoni56** [comment]
Perfect! I actually have no need for an "include" option ;-)

If anything, possibly a way to silence all IGNORING messages, but that is just aestethics!

Thanks.

**Comment by lukejpreston** [comment]
Awesome! I will close issue then. Thanks :D
