### ISSUE TITLE
Filtering in the web view

### ISSUE THREAD

**Issue by thoni56** [lukejpreston/xunit-viewer#62]
Once you have your nice `index.html` with hundreds of tests, I'd like

1. To have all tests are collapsed initially (now they are unfolded)
1. Be able to filter the results according to the three types of results (which have icons in the top level bar)

**Comment by lukejpreston** [comment]
I am not sure what you mean by 3 types

**Comment by thoni56** [comment]
Sorry, I only had three types in my "bar": "Ok", "Failed" and "Ignored", which had icons, but of course there are actually 4, or possibly 5 if you count "Unknown". 

I also found the more detailed filtering available in the menu. It was just my assumption that the icons would also filter, but pushing them only activates the folding of the suite.

So I guess my issue is more of an UX issue than features.
