### ISSUE TITLE
Option to collapse passing tests

### ISSUE THREAD

**Issue by duckinator** [lukejpreston/xunit-viewer#64]
I have a test suite which includes output no matter what, but the output isn't useful unless tests are failing. It'd be nice to have them collapsed when the page loads, either by default or as an option/command-line flag that can be set.

That is to say, this is what I have now:
![Screenshot_2020-01-23 Xunit Viewer](https://user-images.githubusercontent.com/39698/72992702-37f56400-3dc2-11ea-9542-10835b93a320.png)

And it would be nice to have the ability to make it default to this:

![Screenshot_2020-01-23 Xunit Viewer(1)](https://user-images.githubusercontent.com/39698/72992716-3cba1800-3dc2-11ea-900c-d683b2f43add.png)

I think, in terms of implementation, this can be done by changing the `is-active` class to `is-inactive` on all passing tests.

**Comment by lukejpreston** [comment]
This will be resolved when I start work on #59 as you will be able to go to the page with something like `/?test.passed.expanded=false` and it will show as you are expecting and this will couple with the CLI which will do something similar.
