### ISSUE TITLE
Option to hide properties

### ISSUE THREAD

**Issue by mam-ijinus** [lukejpreston/xunit-viewer#65]
hi,

Is ther e an option to hide properties parts, or more globally to set default visual option of the generated report ?

In m'I report, properties takes to much place that we dont see test result.

thanks

**Comment by lukejpreston** [comment]
I think this screenshot might solve your problem

![image](https://user-images.githubusercontent.com/4129128/74230147-b192ba80-4cbb-11ea-89ea-cbef27114ba6.png)

open the menu, expand properties then toggle visible

There is a ticket to make these features available through the URL or CLI so you don't need to open the menu to do this.

*NOTE TO SELF* I think the UI is not clear on these features as a similar question was raised before

**Comment by mam-ijinus** [comment]
Thanks, 

I have seen thee options before it must be check each time we go to the report.

Make this  settable through the URL is a good option.
