### ISSUE TITLE
Symbols get removed from suite name / title

### ISSUE THREAD

**Issue by KoenDG** [lukejpreston/xunit-viewer#76]
* node and npm version

Node: v12.16.1
npm: 6.13.4

* xunit viewer version

6.1.4

* browser

N/A

* sample xml

I've added it in this here pastebin: https://pastebin.com/jFT74Eha
It's been modded slightly to have non-identifiable names.

So I'm using this project at the end of an ansible script, which output the result as a junit file.

The structure is somewhat like a tree, you step down from the top into the branches until you reach that code that has to be executed. Each step is then added to the "testcase_classname".

A line like this will appear:

`<testcase classname="../testfile01.yml:3" name="Suite001: netshoot : junit testsuite001" time="1.278109">`

However, after processing, the colons are gone and the title just reads:

`Suite001 Netshoot Junit Testsuite001`

This makes it unreadable. With many more test results like this, it becomes a great big chore to determine what path exactly has been walked to reach any particular test.

**Comment by lukejpreston** [comment]
can you try v6.2.1 I have removed the title logic

**Comment by KoenDG** [comment]
Hello,

I'm currently working from home, and the internet is kinda bad.

I keep getting this:

```
> npm i xunit-viewer
npm WARN tarball tarball data for xunit-viewer@^6.2.1 (sha512-RU0SN8HRLO8eZ50lT/bu9UuzpmLF0Fr/GLUEp6iQq89WdFxNLTzvqsH718pQw1+s93VUqD5n8lGIRdyXPN6LRg==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for xunit-viewer@^6.2.1 (sha512-RU0SN8HRLO8eZ50lT/bu9UuzpmLF0Fr/GLUEp6iQq89WdFxNLTzvqsH718pQw1+s93VUqD5n8lGIRdyXPN6LRg==) seems to be corrupted. Trying one more time.
```

I'll try some more in the upcoming while.

**Comment by lukejpreston** [comment]
I just used the same version of npm and node as you have (I don't know if you have updated them in 16 days when this was created) and I am not seeing that issue

Try `npm uninstall xunit-viewer` and then reinstall it.

Also, noticed you aren't installing globally using `-g` which isn't a requirement, just wanted to make sure you know where you are installing it to

**Comment by KoenDG** [comment]
Sorry for the delay. I can confirm that the colon symbol now appears as expected.

Thanks for your time.
