### ISSUE TITLE
Test title not selectable

### ISSUE THREAD

**Issue by alexandru-georgescu-hs** [lukejpreston/xunit-viewer#79]
* node and npm version - v12.16.1
* xunit viewer version - 6.2.1
* browser - chrome/firefox
* sample xml

Description: 
- My usecase is having the test title as full classpath so that I can exclude a test when I need it. 
e.g. `live_test.test_widget.ClassName.test_something`

- So I need to copy paste that full path from the html report to my exclude script. I cannot do that because I actually cannot select with the mouse the title cand right click -> copy

**Comment by lukejpreston** [comment]
Once npm is back up there should be a fix for this in `6.2.4`
