### ISSUE TITLE
Ability to change Title and Logo

### ISSUE THREAD

**Issue by marcdacz** [lukejpreston/xunit-viewer#80]
Configs:
* node v10.16.3 and npm v6.9.0
* xunit viewer v6.2.1
* chrome

Firstly, thanks for the continued development of this awesome reporting tool. I've been using it for almost a year now on my own test automation framework. 
Recently after upgrading to the new version (6+) I noticed that the title of the report remains Xunit Viewer despite setting the title option when generating the report. I do notice that the tab title of the browser tab was changed accordingly. 

Also, the existing logo is awesome and all but is it possible to have configs to change the logo as well. So we can customize the overall look of the report?

Thanks and as always, keep up the awesome work!

**Comment by jramapurath-mdsol** [comment]
I am also facing the same Issue after v5.2.0. 
![image](https://user-images.githubusercontent.com/28557185/81162690-3afc1500-8fab-11ea-8aab-4c28f4bb2f0d.png)

![image](https://user-images.githubusercontent.com/28557185/81162713-42232300-8fab-11ea-8741-b5e583746886.png)

**Comment by tanvee38** [comment]
Any progress on this issue? I am having the same problem.

**Comment by lukejpreston** [comment]
I took this out because I didn't think anyone would actually use it! Glad to see this feature is actually useful. I will put it back in as well as add a brand param for the logo.

**Comment by lukejpreston** [comment]
when npm is back up, `6.3.0` will allow you to do the following

```sh
xunit-viewer -r result -o output.html -t "My Title" -b "https://my-brand.png" -f "https://my-favicon.ico"
```

**Comment by tanvee38** [comment]
> when npm is back up, `6.3.0` will allow you to do the following
> 
> ```shell
> xunit-viewer -r result -o output.html -t "My Title" -b "https://my-brand.png" -f "https://my-favicon.ico"
> ```

Thanks a lot for your quick response. Really appreciate it. Thanks for this elegant node library.

**Comment by marcdacz** [comment]
Thanks heaps mate! You're a legend!
