### ISSUE TITLE
How to not clear console when using --console

### ISSUE THREAD

**Issue by marcandjulien** [lukejpreston/xunit-viewer#87]
Using the -c or the --console flag clear the console before outputting the result. I would like to be able to keep the console content. We use xunit-viewer as part of a chain of command and it is annoying to lose the output of everything before xunit-viewer. Would you be open to add an option to not clear the console or to simply not clear the console by default moving forward? I am open to make a PR to this effect if it makes sense for you.

* node and npm version : node v12.16.0 and npm 6.13.4
* xunit viewer version : xunit-viewer@6.3.9

**Comment by lukejpreston** [comment]
It does make sense, shouldn't be too difficult to do and I would be open to a PR.

Here is where the code does the clear <https://github.com/lukejpreston/xunit-viewer/blob/0e2e0ec63a32b9f78e0db96b4c3994e1872bb197/src/cli/terminal.js#L5>

This is where you would put the args <https://github.com/lukejpreston/xunit-viewer/blob/0e2e0ec63a32b9f78e0db96b4c3994e1872bb197/src/cli/args.js>

And here is where you would pass in the options <https://github.com/lukejpreston/xunit-viewer/blob/0e2e0ec63a32b9f78e0db96b4c3994e1872bb197/xunit-viewer.js>

In terms of an arg name `--clear` makes sense and as an alias I am not sure as `-c` has been used. Perhaps `-C` would work, I don't know how yargs works with capital letters

If you create a PR you might have a better idea whilst writing the code. I don't think this part of the code is tested as well as I would like. If you don't want to make a PR I will get to it soon. Thanks to the pandemic I haven't been able to give as much focus to Xunit Viewer as I would have liked but I should be getting back on it this week if it can wait about a week or so?

**Comment by lukejpreston** [comment]
This has been added in `v7.0.0`

**Comment by marcandjulien** [comment]
Thank you for your quick response.
