### ISSUE TITLE
Web performance issues

### ISSUE THREAD

**Issue by clushie** [lukejpreston/xunit-viewer#88]
* node: v12.18.3
* xunit-viewer: 7.0.1
* browser: Version 84.0.4147.135 (Developer Build) (64-bit)
* sample xml: <confidential>

I'm having a big rspec test suite with 1500+ `xml` files being generated. In total they are about ~7MB worth of files.
Generation of the HTML file takes 1-2 Minutes which is actually quite fast, but opening the generated `HTML`-file fails for Firefox and takes minutes to load on Google Chrome (thankfully it does load though)

Few questions:

1. Do you think the web-application could be fixed in reasonable time to be more smart about loading the files into the browser?
2. How can I overwrite  [`initial_state.json`](https://github.com/lukejpreston/xunit-viewer/blob/master/src/app/initial-state.json) to only display Failed tests when I'm opening the browser? Would this make initial displaying easier?
3. Could be `only include failed` added to the CLI-tool output generation? This way I wouldn't have performance issues in my browser anymore since I have almost no tests failing :D

Unfortunately I can't share the generated reports, though if they are really needed I can try to remove all private information first.

**Comment by lukejpreston** [comment]
Wow, 1500 files are a lot and I haven't tested that many before. Does it take a long time to generate the HTML file or is it taking a long time in the browser only (or both)?

I think #52 and #59 would go a long way to solving this issue.

1500 files sounds pretty large. I don't know what you are doing exactly, but perhaps you could break them down into smaller chunks and create multiple Xunit Viewer pages? This might be a short term solution until the above issues are ready.

In terms of test data, it would be nice to get a zip of all those tests in order for me to be able to see how slow it is performing and where the bottle necks are. Unless the tests are unique I can possibly generate a random load of test results and files.

**Comment by clushie** [comment]
Hey @lukejpreston thank you for your instant response.

Generating the HTML is fairly quick, including pulling docker image, npm install, pulling the files it took "7 minutes 39 seconds".

I could investigate how to split those up into different sections, I'd probably try to XML parse for failed tests only and make sure xunit viewer only includes those, though I'd really like to test changing the `initial_state.json` - do you have a tip how I could do this? In the node_modules the js/json is already minified and hard to change.

It is a big rails application and 1500 tests are probably not uncommon for those applications, I'd have to investigate how I can strip them, but I assume Xunit viewer would have a similar performance with any 1500 tests, assuming the body does indeed contain some longer strings.

**Comment by lukejpreston** [comment]
I will just generate random tests, I don't think rspec has anything unique in its output?

Not sure what docker image you are talking about sorry.

You won't be able to update the `initial_state.json` without running the code locally. Otherwise, you can clone the repo locally. A couple of choices spring to mind.

1. change the code, run `npm run build:cli` then run `./bin/xunit-viewer ... your options...`
2. run `npm start`, change the code but also change https://github.com/lukejpreston/xunit-viewer/blob/master/src/index.js#L19 by putting all your XML in there, this is meant to be sample XML only for testing and developing.

I don't think you can realistically do option 2 with all the XML you have.

I am pretty sure the issues I mentioned above will solve your issue and so I am going to link that to this one and leave this one as an investigation to see about running 1.5k tests. Just so I can simulate this better; is it many files, a single file with many tests, or many tests and many files?

**Comment by clushie** [comment]
> Not sure what docker image you are talking about sorry.

Sorry mean just running `npm install` in the official nodejs docker image.

>  Just so I can simulate this better; is it many files, a single file with many tests, or many tests and many files?

So I think those "statistics" are most helpful:

```bash
grep -rc 'testcase name=' | cut -d':' -f 2 | sort -n | uniq -c
```

<details><summary><code>grep -rc 'testcase name=' | cut -d':' -f 2 | sort -n | uniq -c</code></summary>
<code>
   2724 0
   5210 1
    956 2
    438 3
    210 4
    106 5
     63 6
     52 7
     22 8
     15 9
     10 10
      3 11
      8 12
      9 13
      2 14
      4 15
      3 16
      4 17
      1 19
      2 23
      1 24
      1 28
      1 39
      1 46
      1 55
</code>
</expand>

`grep -rc 'testsuite name=' | cut -d':' -f 2 | sort -n | uniq -c` reveals 9847 independent testsuite names.

2724 tests are all `tests="0" time=".*" failures="0" errors="0" skipped="0"` have to check out what is going on there 🙈 

Thank you for your feedback, going to try out option 2 now and potentially document here so people can use it. 😃

**Comment by lukejpreston** [comment]
I have totally forgotten what was going on here since it was so long ago. I did a change so that Xunit Viewer loads up crazy fast in the browser now for a lot of tests. If this hasn't been resolved, please re-raise the issue. Sorry for not getting back to you on this.
