### ISSUE TITLE
Properties and passed tests invisible by default

### ISSUE THREAD

**Issue by Slartibartfast27** [lukejpreston/xunit-viewer#93]
xunit-viewer --version
7.0.1

The generated html files show passed tests and properties by default:

![image](https://user-images.githubusercontent.com/7062914/97551291-17061300-19d3-11eb-8954-41a55aa4180b.png)

I would like to initially have them disabled like this as default:
![image](https://user-images.githubusercontent.com/7062914/97551435-43ba2a80-19d3-11eb-99eb-a86c9595ffa9.png)

Found some options in https://www.npmjs.com/package/xunit-viewer/v/6.0.0-alpha.2 , e.g.
~~~
        --properties.visible false \
        --tests.passed.expanded false \
        --tests.skipped.visible false
~~~

But these options do not seem to have any effect on the initial generated html page using version 7.0.1.

Is there any way in 7.0.1 to initially have passed tests and properties disabled as default?

**Comment by lukejpreston** [comment]
Sorry about the delay here. I have released something that will help. It now defaults to hiding passed and skipped tests and leaves properties visible by default. I don't have these values passing through to the browser, and the filtering in the cli has been broken for a while. Hopefully, v9 will help. I have other issues open to address, namely the React Router and firing filtering in the cli issues. So I will close this or now.
