### ISSUE TITLE
Console view option is ignored and index.html takes forever to load

### ISSUE THREAD

**Issue by rodolphito** [lukejpreston/xunit-viewer#95]
```
$ npm --version
3.5.2
$ node --version
v8.10.0
$ xunit-viewer --version
7.0.1
```
browser: Firefox 82.0 (64-bit)
sample: (unzip and place in a folder named test-reports)
[editmode-results.zip](https://github.com/lukejpreston/xunit-viewer/files/5460731/editmode-results.zip)
sample invocation:
```
xunit-viewer -r test-reports -c
```
Expected behavior: results are printed in the CLI.
Actual behavior: no results are printed, only "Written to: /my/file/path/index.html"

Attempted fixes:
running with `-C`, `-s false`, `--console`, etc. none work.
Additionally, opening the index.html file never loads on Firefox.

**Comment by oscarwallberg** [comment]
I have the same issue. Regarding it taking a long time to load in firefox, I'm assuming it is because the file is incredibly big - atleast for me. Using an xml file that is 2 KB big turns into an html at 1.9 MB, opening it up reveals a huge <script> block.

**Comment by yooouuri** [comment]
2.1MB here, instant makes Chromium and Safari crash. Maybe an idea to separate the javascript / css into different files?

**Comment by lukejpreston** [comment]
Looks like this issue was possible raised twice https://github.com/lukejpreston/xunit-viewer/issues/106
I am going to refer comments over there

**Comment by lukejpreston** [comment]
In this particular data set it looks like it isn't using a version of xunit I am familiar with. Is this xunit 2? If so that could account why it won't render. There is an issue to get this working but I hadn't been given an xunit 2 sample.

**Comment by lukejpreston** [comment]
@rodolphito I have pushed a change into 7.1.6
It won't fix your issue, but it won't crash. I think your issue is an unsupported version of XML. I will work to get it supported now. Thanks for raising this issue. I will let you know when I have something which should work 👍
