### ISSUE TITLE
Option to exit immediately after rendering?

### ISSUE THREAD

**Issue by ianfixes** [lukejpreston/xunit-viewer#98]
It looks like `xunit-viewer` runs indefinitely; the documentation was not clear on this.  I'd like the option to exit immediately after the set of specified results are rendered, so that I can use this program as part of a larger workflow. (Right now it just hangs on the `xunit-viewer` command).

**Comment by lukejpreston** [comment]
I just merged a potential fix for this, could you check version 7.0.3 if this still persists?

**Comment by ianfixes** [comment]
I can check it out. What command line options should cause an exit after the first rendering?

**Comment by lukejpreston** [comment]
@ianfixes whatever command you used in your workflow. I think any command other than `-s` to start a server or `-w` to start a watch it should now exit immediately.

**Comment by ianfixes** [comment]
This works perfectly, thanks!
